# Generated by Django 4.2 on 2023-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telpon', models.IntegerField()),
                ('alamat', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
