# Generated by Django 4.2 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
